name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Pre-check
      options:
        - label: I searched existing issues and docs
          required: true
        - label: I am using the latest release
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Selected text: "..."
        2. Clicked PopClip icon
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Actual behavior
  - type: input
    attributes:
      label: macOS version
      placeholder: e.g., 14.5
  - type: input
    attributes:
      label: PopClip version
      placeholder: e.g., 2024.5
  - type: input
    attributes:
      label: LLMCal version
      placeholder: e.g., v2.0.0
  - type: textarea
    attributes:
      label: Additional context / logs (sanitize secrets)

