name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'LLMCal.popclipext/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get version and template
        id: get_version
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          # Use major template if commit message includes 'BREAKING' or 'major:'
          TEMPLATE=.github/release_template_minor.md
          if git log -1 --pretty=%B | grep -Ei '(breaking|major:)'; then
            TEMPLATE=.github/release_template_major.md
          fi
          echo "template=$TEMPLATE" >> $GITHUB_OUTPUT

      - name: Create ZIP file
        run: |
          cd LLMCal.popclipext
          zip -r ../LLMCal.popclipext.zip *
          cd ..
          mv LLMCal.popclipext.zip LLMCal-latest.popclipext.zip

      - name: Build release notes body
        id: build_notes
        run: |
          TEMPLATE_FILE="${{ steps.get_version.outputs.template }}"
          BODY_FILE="release_body.md"
          cp "$TEMPLATE_FILE" "$BODY_FILE"
          echo "" >> "$BODY_FILE"
          echo "## Changes" >> "$BODY_FILE"
          # Try to get last tag; if none, show recent commits
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            echo "(since $LAST_TAG)" >> "$BODY_FILE"
            git log "$LAST_TAG"..HEAD --pretty=format:"- %s (%h)" --no-merges >> "$BODY_FILE"
          else
            echo "(recent commits)" >> "$BODY_FILE"
            git log -n 30 --pretty=format:"- %s (%h)" --no-merges >> "$BODY_FILE"
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body_path: release_body.md
          files: |
            LLMCal-latest.popclipext.zip
          draft: false
          prerelease: false

      - name: Update repository ZIP file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LLMCal-latest.popclipext.zip
          git commit -m "chore: update extension package to v${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
          git push
